# Generated by Django 5.2.8 on 2025-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
    ]
